# Generated by Django 5.1.7 on 2025-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course_order',
            field=models.IntegerField(default=0),
        ),
    ]
