# Generated by Django 5.1.7 on 2025-04-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userlessoncompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlessoncompleted',
            old_name='student',
            new_name='user',
        ),
    ]
