# Generated by Django 5.1.7 on 2025-04-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userlessoncompleted_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='UserLessonCompleted',
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
    ]
