# Generated by Django 5.1.7 on 2025-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Квиз', 'verbose_name_plural': 'Квизы'},
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'verbose_name': 'Ответ квиза', 'verbose_name_plural': 'Ответы квиза'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Вопрос квиза', 'verbose_name_plural': 'Вопросы квиза'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='course_order',
            field=models.IntegerField(default=0),
        ),
    ]
