# Generated by Django 5.1.7 on 2025-04-04 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_quiz_course_quiz_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuizAttempt',
            new_name='QuizAttempt',
        ),
    ]
