# Generated by Django 5.1.7 on 2025-04-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_quizattempt_attempt_datetime_quizattempt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='student',
            new_name='user',
        ),
    ]
