# Generated by Django 5.1.7 on 2025-04-12 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_student_userlessoncompleted_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
            ],
            options={
                'verbose_name': 'Тег курса',
                'verbose_name_plural': 'Теги курса',
            },
        ),
    ]
