# Generated by Django 5.1.7 on 2025-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_topic_description_remove_topic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
