# Generated by Django 5.1.7 on 2025-05-10 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='news/previews/%d/%m/%Y')),
                ('notification_status', models.CharField(choices=[('not_send', 'Не уведомлять'), ('to_send', 'Уведомить'), ('is_sent', 'Уведомление отправлено')], default='not_send', max_length=100)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/%d/%m/%Y')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'verbose_name': 'Изображение для новости',
                'verbose_name_plural': 'Изображения для новости',
            },
        ),
    ]
