# Generated by Django 5.1.7 on 2025-05-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_subscriptionadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка на рассылку', 'verbose_name_plural': 'Подписки на рассылку'},
        ),
        migrations.DeleteModel(
            name='SubscriptionAdmin',
        ),
    ]
