# Generated by Django 5.1.7 on 2025-03-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userlessoncompleted_userquizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlessoncompleted',
            options={'verbose_name': 'Завершенный урок', 'verbose_name_plural': 'Завершенные уроки'},
        ),
        migrations.AlterModelOptions(
            name='userquizattempt',
            options={'verbose_name': 'Попытка выполнить квиз', 'verbose_name_plural': 'Попытки выполнить квизы'},
        ),
    ]
