# Generated by Django 5.1.7 on 2025-05-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAdmin',
            fields=[
                ('subscription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mailing.subscription')),
            ],
            bases=('mailing.subscription',),
        ),
    ]
