# Generated by Django 5.1.7 on 2025-05-10 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_subscription_options_delete_subscriptionadmin'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('recipient_type', models.CharField(blank=True, choices=[('registered', 'Зарегистрированным'), ('all', 'Всем')], default=None, null=True)),
                ('ready_to_send', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sending_status', models.CharField(blank=True, choices=[('success', 'Отправлено успешно'), ('error', 'Ошибка при отправке')], null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='emailletter',
            name='recipient_list',
            field=models.ManyToManyField(blank=True, to='mailing.subscription'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailing.emailletter'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.emailletter'),
        ),
    ]
