# Generated by Django 5.1.7 on 2025-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_text', models.TextField(default='Демонстрационные материалы', verbose_name='Описание')),
                ('demo_tg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram-канал')),
                ('demo_youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('demo_vk_video', models.URLField(blank=True, null=True, verbose_name='VK Video')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
    ]
