import enum

class MailTrigger(enum.Enum):
    """"""
    GREETING = "GREETING"
    RESET_PASSWORD = "RESET_PASSWORD"
    REGISTER_CONFIRM = "REGISTER_CONFIRM"
    MAIL_CONFIRM = "MAIL_CONFIRM"
    SUPPORT_RESPONSE = "SUPPORT_RESPONSE"
    MAIL_LETTER = "MAIL_LETTER"
