# Generated by Django 5.1.7 on 2025-04-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_student_userlessoncompleted_user'),
        ('quizzes', '0005_remove_quizanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
    ]
