# Generated by Django 5.1.7 on 2025-04-04 05:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_rename_userquizattempt_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempt_datetime',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 5, 50, 59, 462378, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
