# Generated by Django 5.1.7 on 2025-04-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_rename_student_quizattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
